name: smf_get_it
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  mason_logger: ^0.3.3
  smf_contracts:
    path: ../smf_contracts
  path: ^1.9.1
  mustachex: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
